// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmnoG_6yXJIeXIcf9BwF-oPRz3FnIju1M',
    appId: '1:1081547088552:web:7ab6c52acd30d1cc14d89d',
    messagingSenderId: '1081547088552',
    projectId: 'smart-okul',
    authDomain: 'smart-okul.firebaseapp.com',
    storageBucket: 'smart-okul.firebasestorage.app',
    measurementId: 'G-MSK115PP9B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBWOE34ZfGX6RzCsHE8HMgRlGLK1BBv7k',
    appId: '1:1081547088552:android:e2f266e1e78a392014d89d',
    messagingSenderId: '1081547088552',
    projectId: 'smart-okul',
    storageBucket: 'smart-okul.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRm1aNVNwV8-MfCoO9kWAr6wglmozD4zU',
    appId: '1:1081547088552:ios:839e138180537d1014d89d',
    messagingSenderId: '1081547088552',
    projectId: 'smart-okul',
    storageBucket: 'smart-okul.firebasestorage.app',
    iosBundleId: 'com.smartokul.smartOkulMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRm1aNVNwV8-MfCoO9kWAr6wglmozD4zU',
    appId: '1:1081547088552:ios:839e138180537d1014d89d',
    messagingSenderId: '1081547088552',
    projectId: 'smart-okul',
    storageBucket: 'smart-okul.firebasestorage.app',
    iosBundleId: 'com.smartokul.smartOkulMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmnoG_6yXJIeXIcf9BwF-oPRz3FnIju1M',
    appId: '1:1081547088552:web:c50ea4e82f5ecce014d89d',
    messagingSenderId: '1081547088552',
    projectId: 'smart-okul',
    authDomain: 'smart-okul.firebaseapp.com',
    storageBucket: 'smart-okul.firebasestorage.app',
    measurementId: 'G-BTZCDXQB7F',
  );

}